services:
  caddy:
    image: caddy:latest
    restart: always
    container_name: devsign-caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - global_network
    depends_on:
      - frontend
      - backend

  backend:
    restart: always
    container_name: devsign-backend
    build: ./backend
    networks:
      - global_network

  frontend:
    restart: always
    container_name: devsign-frontend
    build: ./frontend
    networks:
      - global_network

  db:
    restart: always #재시작
    container_name: devsign-database
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: devsign4122!
      MYSQL_DATABASE: devsigndb 
      MYSQL_USER: devsignuser
      MYSQL_PASSWORD: devsign4122
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - global_network

volumes:
  db_data:
  caddy_data:
  caddy_config:

networks:
  global_network: