services:
  caddy:
    image: caddy:latest
    restart: always
    container_name: devsign-caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      # ✨ 격리된 루트 데이터 경로
      - /devsign-data/caddy/data:/data
      - /devsign-data/caddy/config:/config
      - /devsign-data/uploads:/uploads  # ✨ 이 줄을 추가합니다! (Caddy가 사진 폴더를 볼 수 있게 됨)
      
    networks:
      - global_network
    depends_on:
      - frontend
      - backend

  backend:
    restart: always
    container_name: devsign-backend
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      # ✨ 게시글 이미지 및 파일 저장용 격리 경로
      - /devsign-data/uploads:/app/uploads
    networks:
      - global_network
    depends_on:
      - db
      - discord-bot
    # 컨테이너 내부에서 'discord-bot'이라는 이름으로 통신하기 위해 링크 보장
    links:
      - discord-bot

  frontend:
    restart: always
    container_name: devsign-frontend
    build: ./frontend
    networks:
      - global_network

  db:
    restart: always
    container_name: devsign-database
    image: mysql:latest
    # ✨ [추가] 한글 깨짐 방지를 위한 UTF-8 설정
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: devsign4122!
      MYSQL_DATABASE: devsigndb 
      MYSQL_USER: devsignuser
      MYSQL_PASSWORD: devsign4122
    volumes:
      # ✨ DB 데이터를 격리된 루트 데이터 경로로 연결
      - /devsign-data/mysql:/var/lib/mysql
    networks:
      - global_network

  # 백엔드의 BOT_BASE 주소와 일치해야 하는 서비스 이름
  discord-bot:
    restart: always
    container_name: devsign-bot
    build: ./discord-bot
    # FastAPI 통신을 위해 8000번 포트 추가
    ports:
      - "8000:8000"
    env_file:
      - /home/devsign/.env_devsign_bot
    networks:
      - global_network
    depends_on:
      - db

networks:
  global_network: